### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Motzee** [Motzee/dingoscope#1]
- [ ] Database Class (CRUD for messages)
- [ ] Previsions Class to generate the json file of the day
- [ ] Form to let everyone add messages in the db (yeeeees X-D)
- [ ] Page to display
- [ ] API
